#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'support/github_project_management'

root = File.expand_path('..', __dir__)
exit DryValidationRust::GitHubProjectManagement::CLI.new(ARGV, root: root).run
