// This file is generated by `bundle exec rake generate:predicates`.
// Do not edit it directly; update predicates.yml instead.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum PredicateOp {
    Gt,
    Gteq,
    Lt,
    Lteq,
    MinSize,
    MaxSize,
    Size,
    Odd,
    Even,
    Unsupported,
}

impl PredicateOp {
    fn from_name(name: &str) -> Self {
        match name {
            "gt" => Self::Gt,
            "gteq" => Self::Gteq,
            "lt" => Self::Lt,
            "lteq" => Self::Lteq,
            "min_size" => Self::MinSize,
            "max_size" => Self::MaxSize,
            "size" => Self::Size,
            "odd" => Self::Odd,
            "even" => Self::Even,
            _ => Self::Unsupported,
        }
    }
}
