# frozen_string_literal: true

# This file is generated by `bundle exec rake generate:predicates`.
# Do not edit it directly; update predicates.yml instead.
module Dry
  module Validation
    module Rust
      class Schema
        NATIVE_PREDICATES = %i[gt gteq lt lteq min_size max_size size odd even].freeze
        RUBY_PREDICATES = %i[format included_in excluded_from eql not_eql].freeze
      end
    end
  end
end
